In [ ]:
                                                  **** Numpy Assignment Questions ****

### 1. What is a Python library? Why do we use Python libraries?

In [ ]:
'''
A Python library is a collection of pre-written functions and tools that help developers perform tasks efficiently
without having to write code from scratch. We use Python libraries for code reusability, efficiency, 
accessing specialized functionality, community support, and interoperability with other libraries.

import numpy as np 
python libraries are collection of modules and function that can be used to perform specific task.
Libraries are prewritten code which save time and efforts.
'''

### 2. What is the difference between Numpy array and List?

In [ ]:
'''
The main differences between a NumPy array and a list are:

#NumPy arrays are homogeneous, meaning all elements must be of the same data type, while lists can contain elements of different data types.
#NumPy arrays offer more efficient storage and operations for numerical data.
#NumPy arrays support vectorized operations, making it easier to perform element-wise operations without explicit looping.
#memory allocation in array is contigious while in list it is random.
#In array homogeneous data is used while in list hetrogeneous data can be used.
#array is statically defined while lists are dynamically defined.
'''

### 3. Find the shape, size and dimension of the following array?

In [1]:
'''
3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Find the shape, size, and dimension of the array
shape = arr.shape
size = arr.size
dimension = arr.ndim

# Print the results
print("Shape of the array:", shape)
print("Size of the array:", size)
print("Dimension of the array:", dimension)


Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


### 4. Write python code to access the first row of the following array?

In [4]:
'''
4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the first row
first_row = arr[0 , :]

# Print the first row
print("First row of the array:", first_row)


First row of the array: [1 2 3 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?

In [6]:
'''
5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the third row and fourth column
element = arr[2, 3]

# Print the third row and fourth column
print("element at the third row and fourth column of the array:", element)


element at the third row and fourth column of the array: 12


### 6. Write code to extract all odd indexed elements from the given numpy array?

In [7]:
'''
6. Write code to extract all odd indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = arr[:, 1::2]
#The 1::2 notation means start from index 1 and step by 2, which effectively selects the elements at odd indices.
# Print the odd-indexed elements
print("Odd-indexed elements of the array:", odd_indexed_elements)


Odd-indexed elements of the array: [[ 2  4]
 [ 6  8]
 [10 12]]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [8]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)


Random 3x3 matrix:
[[0.27509997 0.43764037 0.87851662]
 [0.269348   0.85146163 0.30074917]
 [0.31152026 0.9796925  0.27737527]]


### 8. Describe the difference between np.random.rand and np.random.randn?

In [9]:
'''
The difference between np.random.rand and np.random.randn is that the former generates random values from a uniform distribution 
between 0 and 1, while the latter generates values from a standard normal distribution (mean=0, standard deviation=1).
'''
import numpy as np

# Generate a 2x2 matrix with random numbers from a uniform distribution [0, 1) using np.random.rand
uniform_random_matrix = np.random.rand(2, 2)

# Generate a 2x2 matrix with random numbers from a standard normal distribution using np.random.randn
normal_random_matrix = np.random.randn(2, 2)

print("Random matrix from np.random.rand (uniform distribution):")
print(uniform_random_matrix)
print("\nRandom matrix from np.random.randn (standard normal distribution):")
print(normal_random_matrix)


Random matrix from np.random.rand (uniform distribution):
[[0.32569687 0.7975001 ]
 [0.45077854 0.85247847]]

Random matrix from np.random.randn (standard normal distribution):
[[ 0.30655833 -0.42640899]
 [-0.92719157 -0.21654065]]


### 9. Write code to increase the dimension of the following array?

In [10]:
'''
9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

# Given array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Increasing the dimension using np.newaxis
new_arr = arr[:, :, np.newaxis]

print("Original array:")
print(arr)
print("\nArray with increased dimension:")
print(new_arr)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with increased dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


### 10. How to transpose the following array in NumPy?

In [13]:
'''
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

# Given array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Transpose the array using numpy.transpose()
transposed_arr = np.transpose(arr)

# Alternatively, you can use arr.T attribute for transpose
# transposed_arr = arr.T

print("Original array:")
print(arr)
print("\nTransposed array:")
print(transposed_arr)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Consider the following matrix:

In [ ]:
'''
11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python: 
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A
'''

In [14]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_mul = A * B
print("1. Index wise multiplication:")
print(index_wise_mul)

# 2. Matrix multiplication
matrix_mul = np.dot(A, B.T)  # Transpose B to match dimensions
print("\n2. Matrix multiplication:")
print(matrix_mul)

# 3. Add both the matrices
matrix_addition = A + B
print("\n3. Addition of matrices:")
print(matrix_addition)

# 4. Subtract matrix B from A
matrix_subtraction = A - B
print("\n4. Subtraction of matrix B from A:")
print(matrix_subtraction)

# 5. Divide Matrix B by A
matrix_division = np.divide(B, A)
print("\n5. Division of matrix B by A:")
print(matrix_division)


1. Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Addition of matrices:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Subtraction of matrix B from A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Division of matrix B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12. Which function in Numpy can be used to swap the byte order of an array?

In [15]:
'''
byteswap() function to swap the byte order of an array. 
This function swaps the byte order of the elements in the array. 
'''
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order
arr_swapped = arr.byteswap()

print("Original array:", arr)
print("Swapped array:", arr_swapped)


Original array: [1 2 3 4]
Swapped array: [16777216 33554432 50331648 67108864]


### 13. What is the significance of the np.linalg.inv function?

In [16]:
'''
The np.linalg.inv function calculates the inverse of a matrix. It is significant in linear algebra for solving systems of linear equations.

np.linalg.inv
example- 2x + 3y = 10
         4x - 5y = 20
We can represent this system in matrix form as Ax = b, where:

A = [[2, 3],
     [4, -5]]

x = [x, y]

b = [10, 20]
'''
import numpy as np

# Define matrix A and vector b
A = np.array([[2, 3],
              [4, -5]])

b = np.array([10, 20])

# Compute the inverse of matrix A
A_inv = np.linalg.inv(A)

# Solve for x by multiplying the inverse of A with b
x = np.dot(A_inv, b)

print("Solution for x:", x)


Solution for x: [ 5.00000000e+00 -1.11022302e-16]


### 14. What does the np.reshape function do and how is it used?

In [18]:
#to change the shape (dimensions) of an array without changing its data.
# np.reshape is used to change the shape of an array. It returns a new array with the specified shape.
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2D array with 3 rows and 2 columns
reshaped_arr = np.reshape(arr, (3, 2))

print(reshaped_arr)


[[1 2]
 [3 4]
 [5 6]]


### 15. What is broadcasting in Numpy?

In [19]:
''' 
Broadcasting is a feature in NumPy that allows for arithmetic operations to be performed on arrays of different shapes and sizes.
When operating on arrays with different shapes, NumPy automatically "broadcasts" the smaller array across the larger array 
so that they have compatible shapes for the operation.'''

import numpy as np

# Create a 1D array
x = np.array([1, 2, 3])

# Create a scalar
y = 2

# Multiply the array by the scalar
result = x * y

print(result)  # Output: [2 4 6]


[2 4 6]
